### PR TITLE
Job test generator - update TestCase namespace and method name

### PR DESCRIPTION
**Pull request by ghost**
`lucid make:job DeleteMeNow Migrate`
CURRENT:
```
namespace App\Domains\Migrate\Tests\Jobs;

use App\Domains\Migrate\Jobs\DeleteMeNowJob;
use PHPUnit_Framework_TestCase as TestCase; <<--

class DeleteMeNowJobTest extends TestCase
{
    public function test_deletemenowjob() <<--
    {
        $this->markTestIncomplete();
    }
}
```

CHANGED:
```
namespace App\Domains\Migrate\Tests\Jobs;

use App\Domains\Migrate\Jobs\DeleteMeNowJob;
use Tests\TestCase; <<--

class DeleteMeNowJobTest extends TestCase
{
    public function test_delete_me_now_job() <<--
    {
        $this->markTestIncomplete();
    }
}
```

### CODE REVIEW

**Review by Lazir — APPROVED** [review]

**Comment by Mulkave** [comment]
Would this break for older versions of Laravel?

**Comment by ghost** [comment]
The other versions of Laravel (< 5.4) don’t have namespaces for tests.
Everything was autoloaded by composer, similar with 'database' classmap. I
haven't tested, though

2017-07-27 14:40 GMT+02:00 Abed Halawi <notifications@github.com>:

**Comment by Mulkave** [comment]
Still not sure when to merge your changes @alexgiuvara, is this still required?

**Comment by ghost** [comment]
@Mulkave I no longer work on Lucid project

**Pull request closed without merging**
